### ISSUE TITLE
Use of undeclared type 'WarmUpRequest'

### ISSUE THREAD

**Issue by csandeep** [GetHighstreet/HighstreetWatchApp#1]
I used `carthage checkout` to setup the project (trying this with git submodule wouldn't fetch `Box` library). While compiling I got 2 errors in `ExampleDataParentAppSession.swift`

   * ```~/tmp/HighstreetWatchApp/WatchKitAppExample WatchKit Extension/ExampleDataParentAppSession.swift:54:51: Use of undeclared type 'WarmUpRequest'```
   * ```~/tmp/HighstreetWatchApp/WatchKitAppExample WatchKit Extension/ExampleDataParentAppSession.swift:130:5: 'Product' does not have a member named 'isFavorite'```

![exampledataparentappsession swift 2015-05-26 13-59-35](https://cloud.githubusercontent.com/assets/485867/7819386/6f3ea612-03af-11e5-9293-6f816d353573.jpg)

**Comment by Thomvis** [comment]
Cartfile.resolved was still pointing to a slightly older version of WatchKitCore. Sorry about that. If you run `carthage bootstrap` again it should fetch the latest version. If that doesn't work, please try to clone the repository again from scratch. Let me know if it works!

Also thanks for the note on 'git submodule' not working. I'll look into that.

**Comment by csandeep** [comment]
It works! Love the animation, thanks for open-sourcing this.
